# Generated by Django 3.2.9 on 2022-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
